
server:
  port: 8087
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: ecuser
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/covid19?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis:
#  type-aliases-package: jmu.lsk.entity
logging:
  level:
    jmu.lsk.mapper: debug

#  mapper-locations: classpath:mapper/**.xml