server:
  port: 8089

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/covid19?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

hadoop:
  name-node: hdfs://192.168.69.130:9000
  namespace: /user/hadoop/test1

#showSql
logging:
  level:
    jmu.zsw.dao: debug